In [3]:
import pandas as pd
import numpy as np

## Data preparation
#### • Remove duplicates
#### • Replace values
#### • Filter outliers
#### • Rename Axis
#### • Binning

In [26]:
data = pd.DataFrame({'k1': ['one', 'two'] * 4 + ['two']*2,
'k2': [1, 1, 2, 3, 3, 4, 4,4,-999,-1000]})
data

k1    k2
0  one     1
1  two     1
2  one     2
3  two     3
4  one     3
5  two     4
6  one     4
7  two     4
8  two  -999
9  two -1000

In [5]:
data1 = pd.DataFrame({'k1': ['one', 'two'] * 3 })
data1

k1
0  one
1  two
2  one
3  two
4  one
5  two

In [6]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
dtype: bool

In [7]:
data.duplicated(keep='last')
# keep =‘last’ will return the 'last' observation

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9    False
dtype: bool

In [8]:
data.drop_duplicates(['k1','k2'],keep='last')
# keep =‘last’ will have to return the last observation

k1    k2
0  one     1
1  two     1
2  one     2
3  two     3
4  one     3
6  one     4
7  two     4
8  two  -999
9  two -1000

### replace value

In [9]:
data.replace([-999, -1000], [np.nan, 0],inplace=True)
data

k1   k2
0  one  1.0
1  two  1.0
2  one  2.0
3  two  3.0
4  one  3.0
5  two  4.0
6  one  4.0
7  two  4.0
8  two  NaN
9  two  0.0

In [12]:
data.k1=data.k1.map(lambda x:x.upper())
data.k1
#data.k1 = data.k1.map(lamba x: x.upper())

0    ONE
1    TWO
2    ONE
3    TWO
4    ONE
5    TWO
6    ONE
7    TWO
8    TWO
9    TWO
Name: k1, dtype: object

In [31]:
data.columns=data.columns.map(lambda x:x.upper())
data.columns

Index(['K1', 'K2'], dtype='object')

In [32]:
data

K1    K2
0  one     1
1  two     1
2  one     2
3  two     3
4  one     3
5  two     4
6  one     4
7  two     4
8  two  -999
9  two -1000

In [22]:
#def foo(x):
#    return x.upper()
#foo(data)

In [34]:
# try it question slide 10
data1=pd.DataFrame(np.arange(0,12).reshape(3,4),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])
data1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

## data rename

In [39]:
#data.rename(index=str.title, columns=str.upper, inplace=True)
data.rename(index={'Ohio': 'INDIANA'},columns={'three': 'peekaboo'},inplace=True)
data.rename(index={'Ohio': 'INDIANA'},inplace=True)
data

one  two  peekaboo  four
INDIANA     0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

### Binning

In [42]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)
# right interval inclusion
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [18]:
cats = pd.cut(ages,bins, right= False)
cats
# right side interval is no included

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [21]:
cats=pd.cut(x=ages,bins=bins,labels=['Youth',
'YoungAdult', 'MiddleAged', 'Senior'])
cats

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [22]:
cats.categories

Index(['Youth', 'YoungAdult', 'MiddleAged', 'Senior'], dtype='object')

In [23]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [25]:
pd.value_counts(cats)

Youth         5
MiddleAged    3
YoungAdult    3
Senior        1
dtype: int64

In [94]:
data2=np.random.rand(20)
pd.cut(data2,5,precision=2)
# cut into 4 categories, [(0.022, 0.27] < (0.27, 0.51] < (0.51, 0.75] < (0.75, 1.0]]

[(0.066, 0.25], (0.79, 0.97], (0.25, 0.43], (0.61, 0.79], (0.79, 0.97], ..., (0.43, 0.61], (0.61, 0.79], (0.43, 0.61], (0.61, 0.79], (0.066, 0.25]]
Length: 20
Categories (5, interval[float64]): [(0.066, 0.25] < (0.25, 0.43] < (0.43, 0.61] < (0.61, 0.79] < (0.79, 0.97]]

In [112]:
data3=np.random.rand(1000)
pd.qcut(data3,4,precision=2)
# [(-0.00919, 0.25] < (0.25, 0.51] < (0.51, 0.74] < (0.74, 1.0]]

[(0.48, 0.73], (0.48, 0.73], (0.24, 0.48], (0.24, 0.48], (0.73, 1.0], ..., (0.73, 1.0], (0.48, 0.73], (0.73, 1.0], (0.73, 1.0], (0.48, 0.73]]
Length: 1000
Categories (4, interval[float64]): [(-0.00983, 0.24] < (0.24, 0.48] < (0.48, 0.73] < (0.73, 1.0]]

#### Outliers

### Step 1: Calculate the mean.
### Step 2: Calculate how far away each data point is from the mean using positive distances. These are called absolute deviations.
### Step 3: Add those deviations together.
### Step 4: Divide the sum by the number of data points.

## Three ways to calculate outliers

### Z-score method

In [18]:
import numpy as np

def outliers_z_score(ys):
    threshold = 3
    mean_y = np.mean(ys)
    stdev_y = np.std(ys)
    z_scores = [(y - mean_y) / stdev_y for y in ys]
    return np.where(np.abs(z_scores) > threshold)

In [28]:
ys = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32,1,1000000000,10000000]
outliers_z_score(ys)

(array([13]),)

### Modified Z-score method

In [3]:
import numpy as np

def outliers_modified_z_score(ys):
    threshold = 3.5

    median_y = np.median(ys)
    median_absolute_deviation_y = np.median([np.abs(y - median_y) for y in ys])
    modified_z_scores = [0.6745 * (y - median_y) / median_absolute_deviation_y
                         for y in ys]
    return np.where(np.abs(modified_z_scores) > threshold)

In [29]:
outliers_modified_z_score(ys)

(array([13, 14]),)

### IQR (interquartile range)

In [5]:
import numpy as np

def outliers_iqr(ys):
    quartile_1, quartile_3 = np.percentile(ys, [25, 75])
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    return np.where((ys > upper_bound) | (ys < lower_bound))

In [30]:
outliers_iqr(ys)

(array([13, 14]),)